In [50]:
import pandas as pd

In [79]:
train_path = r'C:\Users\User\Fast_Timing_Model_Estimation_for_new_PVT-master\train\boost\csv\train_ff1p1v125c.csv'

train = pd.read_csv(train_path)
print(train.head())
print('df.shape :',train.shape)

   temperature  voltage  capacitance  rise_capacitance  fall_capacitance  \
0        125.0      1.1     0.001071          0.001056          0.001071   
1        125.0      1.1     0.001071          0.001056          0.001071   
2        125.0      1.1     0.001071          0.001056          0.001071   
3        125.0      1.1     0.001071          0.001056          0.001071   
4        125.0      1.1     0.001372          0.001372          0.001364   

   cell_rise  rise_transition  cell_fall  fall_transition  rise_power  ...  \
0          1                0          0                0           0  ...   
1          0                1          0                0           0  ...   
2          0                0          1                0           0  ...   
3          0                0          0                1           0  ...   
4          1                0          0                0           0  ...   

   value_40  value_41  value_42  value_43  value_44  value_45  value_46  \

In [82]:
test_path = r'C:\Users\User\Fast_Timing_Model_Estimation_for_new_PVT-master\test\boost\csv\lib1_ff1p1v125c_beta_100.csv'

test = pd.read_csv(test_path)
print(test.head())
print('df.shape :',test.shape)

   temperature  voltage  capacitance  rise_capacitance  fall_capacitance  \
0        125.0      1.1     0.001828          0.001793          0.001828   
1        125.0      1.1     0.001828          0.001793          0.001828   
2        125.0      1.1     0.001828          0.001793          0.001828   
3        125.0      1.1     0.001828          0.001793          0.001828   
4        125.0      1.1     0.002030          0.002030          0.001994   

   cell_rise  rise_transition  cell_fall  fall_transition  rise_power  ...  \
0          1                0          0                0           0  ...   
1          0                1          0                0           0  ...   
2          0                0          1                0           0  ...   
3          0                0          0                1           0  ...   
4          1                0          0                0           0  ...   

   value_40  value_41  value_42  value_43  value_44  value_45  value_46  \

In [83]:
import numpy as np 
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
import matplotlib.pyplot as plt

In [84]:
print('train.shape :',train.shape)
print('test.shape :',test.shape)

train.shape : (18858, 74)
test.shape : (5658, 74)


In [85]:
value_columns = []
for i in range(1,50):
    string = 'value_'+str(i)
    value_columns.append(string)   

train_y = train[value_columns]
test_y = test[value_columns]

for col in value_columns:
    train.pop(col)
    test.pop(col)
    
train_x = train
test_x = test

In [86]:
#dataframe -> numpy.array.value
train_x = train_x.values
train_y = train_y.values
    
test_x = test_x.values
test_y = test_y.values

In [94]:
#LinearRegression
from sklearn.linear_model import LinearRegression
model = LinearRegression(fit_intercept=True)
model.fit(train_x, train_y)

predict_test = model.predict(test_x)
print(predict_test.shape)

print(predict_test)
print(test_y)

#compute Accuracy
tmp = abs( test_y - predict_test )/abs( test_y )
#print(tmp)
#print(type(tmp))
#print("-----------------------------------------------------------")
tmp[tmp >1] =1
#print(tmp**2)
square = tmp**2
#print(square.shape[1])
sum1 = np.nansum(square)
print(sum1)
n = square.shape[0] * square.shape[1]
print(n)
score = 100 - 100 * (np.sqrt(sum1/n))
print("accuracy")
print(score)


(5658, 49)
[[0.04150391 0.04528809 0.05706787 ... 0.16595459 0.20495605 0.25628662]
 [0.02282715 0.02709961 0.04089355 ... 0.12335205 0.17016602 0.23382568]
 [0.03875732 0.0423584  0.05352783 ... 0.1505127  0.18591309 0.23205566]
 ...
 [0.0032959  0.0032959  0.00335693 ... 0.00500488 0.00524902 0.00561523]
 [0.00408936 0.00408936 0.00415039 ... 0.0057373  0.00592041 0.00634766]
 [0.0032959  0.0032959  0.00335693 ... 0.00500488 0.00524902 0.00561523]]
[[0.0433743  0.0466042  0.0559071  ... 0.188206   0.215481   0.249492  ]
 [0.0206819  0.023827   0.0344651  ... 0.110126   0.148455   0.204953  ]
 [0.0382812  0.0409856  0.0483389  ... 0.184899   0.205635   0.22974   ]
 ...
 [0.00644223 0.00634674 0.00610983 ... 0.00868021 0.00858076 0.00852174]
 [0.00440699 0.00437299 0.00430219 ... 0.00763188 0.00762144 0.00757476]
 [0.00782422 0.00773023 0.00749895 ... 0.0110371  0.0109334  0.0108708 ]]
93639.89664079493
277242
accuracy
41.883299308692024


C:\Users\User\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: RuntimeWarning: divide by zero encountered in true_divide
  del sys.path[0]
C:\Users\User\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: RuntimeWarning: invalid value encountered in true_divide
  del sys.path[0]
